version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hyphaeos
      - MEMORY_DB_URL=postgresql://postgres:postgres@db:5432/hyphaeos_memory
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hyphaeos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: